# Generated by Django 2.2.6 on 2020-11-15 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_countries', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
